In [1]:
import pandas as pd
import csv

In [2]:
missing_person_csv = "missing_person.csv"
missing_person_df = pd.read_csv(missing_person_csv, sep=';')

missing_person_df.head()

,Current Age From,City Of Last Contact,First Name,Modified Date Time,Middle Name,Last Name,image,Current Age To,Computed Missing Max Age,Computed Missing Min Age,County Of Last Contact,id Formatted,Race / Ethnicity,Date Of Last Contact,State Of Last Contact,Gender,link,namus2Number,Geo Shape,Geo Point 2D
0,69,Tampa,Leeann,2018-05-23T13:39:04-04:00,Coleene,Huffman,https://public.opendatasoft.com/api/v2/catalog...,69,29.0,29.0,Hillsborough,MP19780,White / Caucasian,1978-06-05,FL,Female,https://www.namus.gov//MissingPersons/Case#/19780,19780,"{""type"": ""Point"", ""coordinates"": [-82.45843130...","27.9475267717,-82.4584313022"
1,47,Tucson,Jose,2018-05-09T13:52:08-04:00,Luis,Reynoso Ramirez,https://public.opendatasoft.com/api/v2/catalog...,47,37.0,37.0,Pima,MP16150,Hispanic / Latino,2008-07-30,AZ,Male,https://www.namus.gov//MissingPersons/Case#/16150,16150,"{""type"": ""Point"", ""coordinates"": [-110.9264897...","32.2217479017,-110.926489707"
2,105,Watsonville,Bonnie,2018-05-20T18:29:03-04:00,Elzora,Brashers,https://public.opendatasoft.com/api/v2/catalog...,105,50.0,50.0,Santa Cruz,MP1401,White / Caucasian,1963-09-16,CA,Female,https://www.namus.gov//MissingPersons/Case#/1401,1401,"{""type"": ""Point"", ""coordinates"": [-121.7569076...","36.9102359182,-121.756907618"
3,60,Philadelphia,Marilyn,2018-02-08T23:01:02-05:00,NaN,Lanier,https://public.opendatasoft.com/api/v2/catalog...,60,45.0,45.0,Philadelphia,MP19382,Black / African American,2003-03-30,PA,Female,https://www.namus.gov//MissingPersons/Case#/19382,19382,"{""type"": ""Point"", ""coordinates"": [-75.16379077...","39.9523430652,-75.1637907707"
4,51,Gary,Kirkland,2018-05-09T13:51:34-04:00,C,Young,https://public.opendatasoft.com/api/v2/catalog...,51,45.0,45.0,Lake,MP19610,Black / African American,2012-12-04,IN,Male,https://www.namus.gov//MissingPersons/Case#/19610,19610,"{""type"": ""Point"", ""coordinates"": [-87.34643273...","41.59337742,-87.3464327382"

In [3]:
del missing_person_df['Modified Date Time']
del missing_person_df['Current Age To'] 
del missing_person_df['Computed Missing Max Age']
del missing_person_df['Computed Missing Min Age']
del missing_person_df['link']
del missing_person_df['namus2Number']
del missing_person_df['Geo Shape']
del missing_person_df['id Formatted']

missing_person_df.head()

,Current Age From,City Of Last Contact,First Name,Middle Name,Last Name,image,County Of Last Contact,Race / Ethnicity,Date Of Last Contact,State Of Last Contact,Gender,Geo Point 2D
0,69,Tampa,Leeann,Coleene,Huffman,https://public.opendatasoft.com/api/v2/catalog...,Hillsborough,White / Caucasian,1978-06-05,FL,Female,"27.9475267717,-82.4584313022"
1,47,Tucson,Jose,Luis,Reynoso Ramirez,https://public.opendatasoft.com/api/v2/catalog...,Pima,Hispanic / Latino,2008-07-30,AZ,Male,"32.2217479017,-110.926489707"
2,105,Watsonville,Bonnie,Elzora,Brashers,https://public.opendatasoft.com/api/v2/catalog...,Santa Cruz,White / Caucasian,1963-09-16,CA,Female,"36.9102359182,-121.756907618"
3,60,Philadelphia,Marilyn,NaN,Lanier,https://public.opendatasoft.com/api/v2/catalog...,Philadelphia,Black / African American,2003-03-30,PA,Female,"39.9523430652,-75.1637907707"
4,51,Gary,Kirkland,C,Young,https://public.opendatasoft.com/api/v2/catalog...,Lake,Black / African American,2012-12-04,IN,Male,"41.59337742,-87.3464327382"

In [4]:
missing_person_df.rename(columns = {'Current Age From':'age', 'City Of Last Contact':'city_last_seen', 'First Name': 
                                   'first', 'Middle Name': 'middle', 'Last Name':'last', 'County Of Last Contact': 'county_last_seen', 'Race / Ethnicity': 'race', 'Date Of Last Contact': 'date_last_seen', 'State Of Last Contact':'state_last_seen', 'Gender':'gender', 'Geo Point 2D': 'lat_long' }, inplace = True)




missing_person_df.head()

,age,city_last_seen,first,middle,last,image,county_last_seen,race,date_last_seen,state_last_seen,gender,lat_long
0,69,Tampa,Leeann,Coleene,Huffman,https://public.opendatasoft.com/api/v2/catalog...,Hillsborough,White / Caucasian,1978-06-05,FL,Female,"27.9475267717,-82.4584313022"
1,47,Tucson,Jose,Luis,Reynoso Ramirez,https://public.opendatasoft.com/api/v2/catalog...,Pima,Hispanic / Latino,2008-07-30,AZ,Male,"32.2217479017,-110.926489707"
2,105,Watsonville,Bonnie,Elzora,Brashers,https://public.opendatasoft.com/api/v2/catalog...,Santa Cruz,White / Caucasian,1963-09-16,CA,Female,"36.9102359182,-121.756907618"
3,60,Philadelphia,Marilyn,NaN,Lanier,https://public.opendatasoft.com/api/v2/catalog...,Philadelphia,Black / African American,2003-03-30,PA,Female,"39.9523430652,-75.1637907707"
4,51,Gary,Kirkland,C,Young,https://public.opendatasoft.com/api/v2/catalog...,Lake,Black / African American,2012-12-04,IN,Male,"41.59337742,-87.3464327382"

In [5]:
#missing_person_df.to_csv('cleaned_csv.csv', index=False)
# missing_person_df.to_csv('cleaned_csv')